### ISSUE TITLE
Error: Schema must contain uniquely named types but contains multiple types named "RemarkHeadingLevels"

### ISSUE THREAD

**Issue by JesusPerez** [drehimself/gridsome-portfolio-starter#59]
node -v  v12.13.0 
npm -v  6.13.0
MacOS Catalina or  Linux 

Just simply runs:
```bash
npm install
yarn upgrade
npm build 
```

Initializing plugins...
Load sources - 0.19s
Error: Schema must contain uniquely named types but contains multiple types named "RemarkHeadingLevels".
    at typeMapReducer (/gridsome-portfolio-starter/node_modules/graphql/type/schema.js:262:13)
    at Array.reduce (<anonymous>)
    at typeMapReducer (/gridsome-portfolio-starter/node_modules/graphql/type/schema.js:285:34)
    at typeMapReducer (/gridsome-portfolio-starter/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/gridsome-portfolio-starter/node_modules/graphql/type/schema.js:145:28)
    at SchemaComposer.buildSchema (/gridsome-portfolio-starter/node_modules/graphql-compose/lib/SchemaComposer.js:131:12)
    at Schema.buildSchema (/gridsome-portfolio-starter/node_modules/gridsome/lib/app/Schema.js:35:35)
    at Plugins.createSchema (/gridsome-portfolio-starter/node_modules/gridsome/lib/app/Plugins.js:94:22)

**Comment by drehimself** [comment]
Yeah, I get this too when updating to the latest versions of vue-remark and/or transformer-remark (that's why I didn't merge the PRs). I will take a look at this when I have time, or if you/someone figures it out, let me know!

**Comment by rolbr** [comment]
I'm also getting this. Doesn't seem to be a problem with this repo though, as it's also occuring on the main project: https://github.com/gridsome/gridsome/issues/815

**Comment by distinctperspective** [comment]
Its happening to me even after downgrading vue.remark
